name: CI Pipeline for Pull Requests

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  # YAML Lint job - runs after auto-gen-date
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Install yamllint
        run: python3 -m pip install yamllint

      - name: Lint YAML files
        run: "yamllint -f github -d '{extends: default, rules: {line-length: disable}}' _data/guides.yml"

  sort-yaml-by-title:
    name: Sort YAML files by title
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
          fetch-depth: 0

      - name: Sort Keys by title
        uses: mikefarah/yq@master
        with:
            cmd: yq -i 'sort_by(.title)' _data/guides.yml

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: Auto-sort _data/guides.yml by title [skip ci]"
          file_pattern: "_data/guides.yml"